import type { Exercise, MuscleGroupId } from "./types"

export const muscleGroups: MuscleGroupId[] = [
  "chest",
  "back",
  "legs",
  "shoulders",
  "biceps",
  "triceps",
  "core",
  "glutes",
  "cardio",
  "full_body",
  "other",
]

export const starterExercises: Exercise[] = [
  exercise("bench_press", "Bench press", "Жим лежа", ["chest", "triceps"]),
  exercise("incline_dumbbell_press", "Incline dumbbell press", "Жим гантелей на наклонной", ["chest"]),
  exercise("dumbbell_bench_press", "Dumbbell bench press", "Жим гантелей лежа", ["chest", "triceps"]),
  exercise("chest_fly", "Chest fly", "Разведение рук на грудь", ["chest"]),
  exercise("cable_crossover", "Cable crossover", "Кроссовер на блоках", ["chest"]),
  exercise("push_up", "Push-up", "Отжимания", ["chest", "triceps"], "bodyweight_reps"),
  exercise("incline_barbell_press", "Incline barbell press", "Жим штанги на наклонной", ["chest", "triceps"]),
  exercise("decline_bench_press", "Decline bench press", "Жим лежа на наклонной вниз", ["chest", "triceps"]),
  exercise("decline_dumbbell_press", "Decline dumbbell press", "Жим гантелей на наклонной вниз", ["chest", "triceps"]),
  exercise("machine_chest_press", "Machine chest press", "Жим от груди в тренажере", ["chest", "triceps"]),
  exercise("smith_machine_bench_press", "Smith machine bench press", "Жим лежа в Смите", ["chest", "triceps"]),
  exercise("pec_deck_fly", "Pec deck fly", "Бабочка в тренажере", ["chest"]),
  exercise("dumbbell_pullover", "Dumbbell pullover", "Пуловер с гантелью", ["chest", "back"]),
  exercise("squeeze_press", "Squeeze press", "Жим гантелей с сведением", ["chest", "triceps"]),
  exercise("single_arm_cable_fly", "Single-arm cable fly", "Кроссовер одной рукой", ["chest"]),
  exercise("ring_push_up", "Ring push-up", "Отжимания на кольцах", ["chest", "triceps", "core"], "bodyweight_reps"),

  exercise("lat_pulldown", "Lat pulldown", "Тяга верхнего блока", ["back"]),
  exercise("seated_cable_row", "Seated cable row", "Горизонтальная тяга", ["back"]),
  exercise("barbell_row", "Barbell row", "Тяга штанги в наклоне", ["back"]),
  exercise("dumbbell_row", "Dumbbell row", "Тяга гантели в наклоне", ["back"]),
  exercise("pull_up", "Pull-up", "Подтягивания", ["back", "biceps"], "bodyweight_reps"),
  exercise("assisted_pull_up", "Assisted pull-up", "Подтягивания с поддержкой", ["back", "biceps"]),
  exercise("back_extension", "Back extension", "Гиперэкстензия", ["back", "glutes"], "bodyweight_reps"),
  exercise("chest_supported_row", "Chest-supported row", "Тяга с опорой грудью", ["back"]),
  exercise("t_bar_row", "T-bar row", "Тяга Т-грифа", ["back"]),
  exercise("straight_arm_pulldown", "Straight-arm pulldown", "Пуловер на верхнем блоке", ["back"]),
  exercise("machine_row", "Machine row", "Тяга в тренажере", ["back"]),
  exercise("single_arm_cable_row", "Single-arm cable row", "Тяга блока одной рукой", ["back"]),
  exercise("inverted_row", "Inverted row", "Австралийские подтягивания", ["back", "biceps"], "bodyweight_reps"),
  exercise("neutral_grip_pull_up", "Neutral-grip pull-up", "Подтягивания нейтральным хватом", ["back", "biceps"], "bodyweight_reps"),
  exercise("chin_up", "Chin-up", "Подтягивания обратным хватом", ["back", "biceps"], "bodyweight_reps"),
  exercise("meadows_row", "Meadows row", "Тяга Медоуза", ["back"]),
  exercise("seal_row", "Seal row", "Тяга лежа на скамье", ["back"]),
  exercise("good_morning", "Good morning", "Наклоны со штангой на плечах", ["back", "glutes", "legs"]),
  exercise("snatch_grip_deadlift", "Snatch-grip deadlift", "Становая тяга рывковым хватом", ["back", "legs", "full_body"]),
  exercise("rack_pull", "Rack pull", "Тяга с пинов", ["back", "full_body"]),
  exercise("superman_hold", "Superman hold", "Супермен удержание", ["back", "glutes"], "time"),

  exercise("barbell_squat", "Barbell squat", "Присед со штангой", ["legs", "glutes"]),
  exercise("leg_press", "Leg press", "Жим ногами", ["legs", "glutes"]),
  exercise("leg_extension", "Leg extension", "Разгибание ног", ["legs"]),
  exercise("lying_leg_curl", "Lying leg curl", "Сгибание ног лежа", ["legs"]),
  exercise("romanian_deadlift", "Romanian deadlift", "Румынская тяга", ["legs", "glutes", "back"]),
  exercise("walking_lunge", "Walking lunge", "Выпады в ходьбе", ["legs", "glutes"]),
  exercise("standing_calf_raise", "Standing calf raise", "Подъемы на носки стоя", ["legs"]),
  exercise("seated_calf_raise", "Seated calf raise", "Подъемы на носки сидя", ["legs"]),
  exercise("front_squat", "Front squat", "Фронтальный присед", ["legs", "glutes", "core"]),
  exercise("goblet_squat", "Goblet squat", "Гоблет-присед", ["legs", "glutes"]),
  exercise("hack_squat", "Hack squat", "Гакк-присед", ["legs", "glutes"]),
  exercise("bulgarian_split_squat", "Bulgarian split squat", "Болгарские выпады", ["legs", "glutes"]),
  exercise("split_squat", "Split squat", "Сплит-присед", ["legs", "glutes"]),
  exercise("step_up", "Step-up", "Зашагивания на тумбу", ["legs", "glutes"]),
  exercise("reverse_lunge", "Reverse lunge", "Обратные выпады", ["legs", "glutes"]),
  exercise("seated_leg_curl", "Seated leg curl", "Сгибание ног сидя", ["legs"]),
  exercise("nordic_curl", "Nordic curl", "Нордические сгибания", ["legs"], "bodyweight_reps"),
  exercise("sissy_squat", "Sissy squat", "Сисси-присед", ["legs"], "bodyweight_reps"),
  exercise("sumo_deadlift", "Sumo deadlift", "Сумо-тяга", ["legs", "glutes", "back", "full_body"]),
  exercise("trap_bar_deadlift", "Trap bar deadlift", "Тяга с трэп-грифом", ["legs", "glutes", "full_body"]),
  exercise("box_squat", "Box squat", "Присед на коробку", ["legs", "glutes"]),
  exercise("zercher_squat", "Zercher squat", "Присед Зерхера", ["legs", "core", "full_body"]),
  exercise("pause_squat", "Pause squat", "Присед с паузой", ["legs", "glutes"]),
  exercise("cossack_squat", "Cossack squat", "Казачий присед", ["legs", "glutes"], "bodyweight_reps"),
  exercise("donkey_calf_raise", "Donkey calf raise", "Подъемы на носки в наклоне", ["legs"]),
  exercise("tibialis_raise", "Tibialis raise", "Подъемы носков на голень", ["legs"]),

  exercise("shoulder_press", "Shoulder press", "Жим на плечи", ["shoulders", "triceps"]),
  exercise("dumbbell_lateral_raise", "Dumbbell lateral raise", "Махи гантелями в стороны", ["shoulders"]),
  exercise("rear_delt_fly", "Rear delt fly", "Разведение на заднюю дельту", ["shoulders"]),
  exercise("front_raise", "Front raise", "Подъем перед собой", ["shoulders"]),
  exercise("face_pull", "Face pull", "Тяга каната к лицу", ["shoulders", "back"]),
  exercise("arnold_press", "Arnold press", "Жим Арнольда", ["shoulders", "triceps"]),
  exercise("push_press", "Push press", "Швунг жимовой", ["shoulders", "triceps", "full_body"]),
  exercise("machine_shoulder_press", "Machine shoulder press", "Жим на плечи в тренажере", ["shoulders", "triceps"]),
  exercise("upright_row", "Upright row", "Тяга к подбородку", ["shoulders", "triceps"]),
  exercise("cable_lateral_raise", "Cable lateral raise", "Махи в стороны на блоке", ["shoulders"]),
  exercise("leaning_lateral_raise", "Leaning lateral raise", "Махи в стороны с наклоном", ["shoulders"]),
  exercise("reverse_pec_deck", "Reverse pec deck", "Обратная бабочка", ["shoulders"]),
  exercise("landmine_press", "Landmine press", "Жим в упоре на минах", ["shoulders", "triceps", "core"]),
  exercise("scarecrow_raise", "Scarecrow raise", "Подъемы scarecrow", ["shoulders"]),
  exercise("cuban_press", "Cuban press", "Кубинский жим", ["shoulders"]),

  exercise("barbell_curl", "Barbell curl", "Подъем штанги на бицепс", ["biceps"]),
  exercise("dumbbell_curl", "Dumbbell curl", "Подъем гантелей на бицепс", ["biceps"]),
  exercise("hammer_curl", "Hammer curl", "Молотковые сгибания", ["biceps"]),
  exercise("preacher_curl", "Preacher curl", "Сгибания на скамье Скотта", ["biceps"]),
  exercise("cable_curl", "Cable curl", "Сгибания на блоке", ["biceps"]),
  exercise("incline_dumbbell_curl", "Incline dumbbell curl", "Сгибания гантелей на наклонной", ["biceps"]),
  exercise("concentration_curl", "Concentration curl", "Концентрированные сгибания", ["biceps"]),
  exercise("ez_bar_curl", "EZ-bar curl", "Подъем EZ-штанги на бицепс", ["biceps"]),
  exercise("spider_curl", "Spider curl", "Спайдер-сгибания", ["biceps"]),
  exercise("reverse_curl", "Reverse curl", "Обратные сгибания", ["biceps", "other"]),
  exercise("bayesian_curl", "Bayesian curl", "Байезиан-сгибания", ["biceps"]),
  exercise("machine_preacher_curl", "Machine preacher curl", "Сгибания в тренажере Скотта", ["biceps"]),

  exercise("triceps_pushdown", "Triceps pushdown", "Разгибание рук на блоке", ["triceps"]),
  exercise("overhead_triceps_extension", "Overhead triceps extension", "Разгибание из-за головы", ["triceps"]),
  exercise("close_grip_bench_press", "Close-grip bench press", "Жим узким хватом", ["triceps", "chest"]),
  exercise("dip", "Dip", "Отжимания на брусьях", ["triceps", "chest"], "bodyweight_reps"),
  exercise("skull_crusher", "Skull crusher", "Французский жим лежа", ["triceps"]),
  exercise("rope_pushdown", "Rope pushdown", "Разгибание канатом", ["triceps"]),
  exercise("single_arm_pushdown", "Single-arm pushdown", "Разгибание одной рукой на блоке", ["triceps"]),
  exercise("bench_dip", "Bench dip", "Обратные отжимания от скамьи", ["triceps"], "bodyweight_reps"),
  exercise("cable_overhead_extension", "Cable overhead extension", "Разгибание над головой на блоке", ["triceps"]),
  exercise("lying_triceps_extension", "Lying triceps extension", "Разгибание рук лежа", ["triceps"]),
  exercise("cross_body_triceps_extension", "Cross-body triceps extension", "Разгибание через корпус", ["triceps"]),
  exercise("machine_dip", "Machine dip", "Отжимания в тренажере", ["triceps", "chest"]),

  exercise("plank", "Plank", "Планка", ["core"], "time"),
  exercise("side_plank", "Side plank", "Боковая планка", ["core"], "time"),
  exercise("crunch", "Crunch", "Скручивания", ["core"], "bodyweight_reps"),
  exercise("hanging_leg_raise", "Hanging leg raise", "Подъем ног в висе", ["core"], "bodyweight_reps"),
  exercise("cable_crunch", "Cable crunch", "Скручивания на блоке", ["core"]),
  exercise("ab_wheel_rollout", "Ab wheel rollout", "Роллаут с колесом", ["core"], "bodyweight_reps"),
  exercise("russian_twist", "Russian twist", "Русские скручивания", ["core"], "bodyweight_reps"),
  exercise("mountain_climber", "Mountain climber", "Альпинист", ["core", "full_body"], "bodyweight_reps"),
  exercise("toe_touch_crunch", "Toe touch crunch", "Скручивания к носкам", ["core"], "bodyweight_reps"),
  exercise("dead_bug", "Dead bug", "Дэд баг", ["core"], "bodyweight_reps"),
  exercise("hollow_hold", "Hollow hold", "Полая лодочка", ["core"], "time"),
  exercise("hanging_knee_raise", "Hanging knee raise", "Подъем коленей в висе", ["core"], "bodyweight_reps"),
  exercise("reverse_crunch", "Reverse crunch", "Обратные скручивания", ["core"], "bodyweight_reps"),
  exercise("v_up", "V-up", "V-скручивания", ["core"], "bodyweight_reps"),
  exercise("pallof_press", "Pallof press", "Паллоф-пресс", ["core"]),

  exercise("hip_thrust", "Hip thrust", "Ягодичный мост со штангой", ["glutes"]),
  exercise("glute_bridge", "Glute bridge", "Ягодичный мост", ["glutes"], "bodyweight_reps"),
  exercise("cable_kickback", "Cable kickback", "Отведение ноги в кроссовере", ["glutes"]),
  exercise("barbell_glute_bridge", "Barbell glute bridge", "Ягодичный мост со штангой на полу", ["glutes"]),
  exercise("frog_pump", "Frog pump", "Фрог-памп", ["glutes"], "bodyweight_reps"),
  exercise("kettlebell_swing", "Kettlebell swing", "Махи гирей", ["glutes", "full_body"]),
  exercise("single_leg_hip_thrust", "Single-leg hip thrust", "Ягодичный мост на одной ноге", ["glutes"], "bodyweight_reps"),
  exercise("cable_pull_through", "Cable pull-through", "Тяга между ног на блоке", ["glutes"]),
  exercise("curtsy_lunge", "Curtsy lunge", "Реверанс-выпады", ["glutes", "legs"]),
  exercise("abduction_machine", "Abduction machine", "Разведение ног в тренажере", ["glutes"]),

  exercise("treadmill_run", "Treadmill run", "Беговая дорожка", ["cardio"], "distance_time"),
  exercise("stationary_bike", "Stationary bike", "Велотренажер", ["cardio"], "distance_time"),
  exercise("rowing_machine", "Rowing machine", "Гребной тренажер", ["cardio", "full_body"], "distance_time"),
  exercise("elliptical", "Elliptical", "Эллипсоид", ["cardio"], "distance_time"),
  exercise("stair_climber", "Stair climber", "Лестничный тренажер", ["cardio"], "distance_time"),
  exercise("jump_rope", "Jump rope", "Скакалка", ["cardio"], "time"),
  exercise("outdoor_run", "Outdoor run", "Бег на улице", ["cardio"], "distance_time"),
  exercise("assault_bike", "Assault bike", "Эйрбайк", ["cardio", "full_body"], "distance_time"),
  exercise("brisk_walk", "Brisk walk", "Быстрая ходьба", ["cardio"], "distance_time"),

  exercise("deadlift", "Deadlift", "Становая тяга", ["full_body", "back", "legs"]),
  exercise("clean_and_press", "Clean and press", "Взятие и жим", ["full_body"]),
  exercise("burpee", "Burpee", "Берпи", ["full_body"], "bodyweight_reps"),
  exercise("thruster", "Thruster", "Трастер", ["full_body"]),
  exercise("kettlebell_snatch", "Kettlebell snatch", "Рывок гири", ["full_body"]),
  exercise("kettlebell_clean_and_press", "Kettlebell clean and press", "Взятие гири на грудь и жим", ["full_body"]),
  exercise("man_maker", "Man maker", "Манмейкер", ["full_body"], "bodyweight_reps"),
  exercise("farmers_walk", "Farmer's walk", "Фермерская прогулка", ["full_body", "core"], "distance_time"),

  exercise("shrug", "Shrug", "Шраги", ["other", "shoulders"]),
  exercise("wrist_curl", "Wrist curl", "Сгибание кистей", ["other"]),
  exercise("neck_flexion", "Neck flexion", "Сгибание шеи", ["other"]),
  exercise("neck_extension", "Neck extension", "Разгибание шеи", ["other"]),
  exercise("wrist_extension", "Wrist extension", "Разгибание кистей", ["other"]),
  exercise("grip_crush", "Grip crush", "Сжатие эспандера", ["other"]),
]

function exercise(
  id: string,
  en: string,
  ru: string,
  muscleGroupIds: MuscleGroupId[],
  trackingMode: Exercise["trackingMode"] = "weight_reps"
): Exercise {
  return {
    id,
    name: { en, ru },
    muscleGroupIds,
    trackingMode,
    builtIn: true,
  }
}
